name: Ruff
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
      - name: Run Ruff
        run: ruff check --output-format=github ./src
